language: python

sudo: required

dist: "xenial"

python:
  - "3.7"

addons:
  postgresql: "9.4"
  chrome: stable

services:
  - postgresql

before_install:
  - pip install -U pip
  - export DJANGO_SETTINGS_MODULE=bzw_ops.settings
  - export PYTHONPATH=$PYTHONPATH:$HOME/builds/adrianboyko/xerocraft-django
  - export PIP_USE_MIRRORS=true

install:
  # For Chrome Driver install discussion,
  # See https://www.amihaiemil.com/2017/07/14/selenium-headless-chrome-travis.html
  # And https://gist.github.com/ziadoz/3e8ab7e944d02fe872c3454d17af31a5
  - CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database test_db;' -U postgres

script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - python manage.py collectstatic
  - python manage.py test
